  apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: shine-retail-app  # Change from: userprofile-blue-green
    namespace: argocd
  spec:
    project: default
    source:
      repoURL: https://github.com/nanineelapu/Shine-GitOps-Project.git
      targetRevision: main
      path: Retail-chart
      helm:
        values: |
          userprofile:
            activeVersion: blue
    destination:
      server: https://kubernetes.default.svc
      namespace: retail
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
