datadog:
  site: "ap1.datadoghq.com"
  clusterName: "shinecluster"
  apiKeyExistingSecret: "datadog-secret"
  clusterChecks:
    enabled: true
  orchestratorExplorer:
    enabled: true
  tags:
    - "env:prod"
  apm:
    instrumentation:
      enabled: true
      targets:
        - name: "default-target"
          ddTraceVersions:
            java: "1"
            python: "4"
            js: "5"
            php: "1"
            dotnet: "3"
            ruby: "2"
  logs:
    enabled: true
    containerCollectAll: true
  autoscaling:
    workload:
      enabled: true
  kubernetesEvents:
    unbundleEvents: true
registry: "public.ecr.aws/datadog"
